### ISSUE TITLE
Feature: Load Server Configuration from YAML or JSON

### ISSUE THREAD

**Issue by krkarma777** [krkarma777/Javelin#26]
**Description:**  
Allow the server to load its configuration (such as port, thread limits, timeouts, etc.) from external YAML or JSON files. This makes it easier to manage settings across different environments (dev, staging, prod).

**Example Use Case:**
A `config.yaml` file might look like:
```yaml
server:
  port: 8080
  thread-limit: 1000
  static-path: ./public
  enable-cors: true
```

**Acceptance Criteria:**
- [ ] Support loading configuration from both `.yaml` and `.json` files
- [ ] Apply configuration values at server startup
- [ ] Provide defaults if config is missing or incomplete
- [ ] Allow overriding via environment variables or CLI flags
- [ ] Validate configuration structure and types
